Feature 9/ns di filter list
the-collab-lab/tcl-39-smart-shopping-list pull request #25
Opened 2022-02-10 19:05 UTC by Dara97

## Description

Se filtran los ítems mientras se escribe. Cuando el campo tiene texto el usuario lo puede eliminar con el botón junto al campo de texto.  La búsqueda se puede hacer con cualquier parte del nombre del ítem.

## Related Issue

Closes #9 

## Acceptance Criteria

* Mostrar un campo de texto en la parte superior de la lista de la compra.
* A medida que el usuario escribe en el campo, la lista debe reducirse para mostrar sólo los elementos que contienen el texto que el usuario introdujo en el campo de filtro.
* Cuando el campo tiene texto, el usuario debe poder tocar un elemento de la interfaz de usuario (por ejemplo, con un botón "X" junto al campo) para limpiar el campo.
* El texto del filtro debe coincidir con cualquier parte del nombre del artículo (es decir, no debe coincidir sólo con el inicio de la cadena)

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

## Updates

### Before

![antes](https://user-images.githubusercontent.com/75139726/153476674-138f7c05-4b96-4cd7-90b6-3ceb296606be.JPG)

### After

![despues1](https://user-images.githubusercontent.com/75139726/153476912-f245cad6-7329-497f-8aca-71158796ae87.JPG)

![despues2](https://user-images.githubusercontent.com/75139726/153476929-cae9e4c1-2da0-4983-8860-487621095179.JPG)

![despues3](https://user-images.githubusercontent.com/75139726/153478407-ea74cfbb-206e-443f-aa1c-903d1239544c.JPG)

## Testing Steps / QA Criteria

Al ingresar a la lista de productos se observa el campo de texto para filtrarlos.

- Ingresa el nombre del producto que necesites filtrar, no necesariamente se debe escribir todo el nombre, pues va filtrando mientras se ingresan las letras.
- Puedes borrar el texto del campo con el botón "x", así se muestra toda la lista de ítems de nuevo.

2022-02-10 21:57 UTC, candrepa1 approved these changes

2022-02-10 21:57 UTC, candrepa1 commented on src/components/formProducts/FormProducts.js
> +    : items.filter((filterItem) =>
nice!

2022-02-10 21:57 UTC, candrepa1 commented on src/components/formProducts/FormProducts.js
> +    e.preventDefault();
I don't think you need to prevent the form since the button is not `type='submit'`

2022-02-10 21:57 UTC, candrepa1 commented on src/components/formProducts/FormProducts.js
> +            G
?

2022-02-10 22:04 UTC, Dara97 commented on src/components/formProducts/FormProducts.js
> +    e.preventDefault();
Cuando le daba al botón "x" se cargaba el loading programado entonces por eso se lo implemento.

2022-02-10 22:05 UTC, Dara97 commented on src/components/formProducts/FormProducts.js
> +            G
Ya lo arreglo.

2022-02-10 22:09 UTC, candrepa1 commented on src/components/formProducts/FormProducts.js
> +    e.preventDefault();
then I believe it is better to change the button type to 'button', since it is what is actually doing

2022-02-10 22:41 UTC, Dara97 commented on src/components/formProducts/FormProducts.js
> +    e.preventDefault();
tienes razón, ya lo cambie, gracias !

2022-02-10 23:11 UTC, FauricioValencia commented on src/components/formProducts/FormProducts.js
> +  const resetInput = () => {
what do you think if left in just one line 
`const resetInput = () => setItemName('');`

2022-02-10 23:12 UTC, FauricioValencia approved these changes

2022-02-10 23:32 UTC, alxmcr commented on src/components/formProducts/FormProducts.css
> +  outline: none;
Interesting! Remove borders! 😄

2022-02-10 23:52 UTC, alxmcr commented on src/components/formProducts/FormProducts.js
>          items.map((item, index) => (
**Sugerencia:**

Cuando se busca un item por un nombre que "no existe" en la base de datos, se podría reutilizar el código que se utilizo en `List_Products` y el component `ListEmpty`. Debido a que, cuando sucede este caso, no se da ningun tipo de "feedback" al usuario o al menos no hay un mensaje que diga: 

> "Sin resultados. No existe algun producto con el nombre 'XYZ' en la base de datos. (Add item button)" 

or

> "No results. There isn't any product with 'XYZ' as the name in the database". (Add item button)

![image](https://user-images.githubusercontent.com/8689897/153516586-d2feef88-0196-4298-b618-048496b99cd9.png)

2022-02-11 00:13 UTC, alxmcr commented on src/components/formProducts/FormProducts.js
> +    : items.filter((filterItem) =>
Estoy realmente, sorprendido como estas lineas.... wow!!! es magía pura... sin embargo... como sugerencia, consideren usar estados y `useEffect`

```suggestion
  const [itemsFiltered, setItemsFiltered] = useState(items);
  //... more code
    useEffect(() => {
    if (itemName === '') {
      setItemsFiltered(items)
    } else {
      setItemsFiltered(items.filter((filterItem) =>
        filterItem.name.toLowerCase().includes(itemName.toLocaleLowerCase())))
    }
  }, [itemName, items])
  //... more code
  {itemsFiltered && // more code}
```

2022-02-11 00:14 UTC, Dara97 commented on src/components/formProducts/FormProducts.js
> +  const resetInput = () => {
Si ya lo cambie, gracias !

2022-02-11 00:16 UTC, alxmcr approved these changes
Approved! ✔️ 

Buen trabajo Natalia y Dara! 💯  Deje algunos comentarios y sugerencias pero nada que realice algun bloqueo. 😄

2022-02-11 14:56 UTC, JGitHub25 requested changes
El filtro funciona genial. Lo único es asegurarse de que la marca de compra se refleje correctamente en él.

2022-02-11 14:56 UTC, JGitHub25 commented on src/components/formProducts/FormProducts.css
> +  outline: none;
Se necesita el outline? No vi que modificara nada...

2022-02-11 14:56 UTC, JGitHub25 commented on src/components/formProducts/FormProducts.js
> +    : items.filter((filterItem) =>
El filtro funciona súper pero creo que sí sería mejor usar estados por el siguiente detalle: cuando se marca un producto como comprado e inmediatamente se busca con el filtro éste aparece desmarcado.

Creo que esto pasa porque el filtro trabaja sobre el `items` inicial (donde el producto no estaba marcado). No es sino hasta que vuelve a haber un render de `ListProducts` que las marcas se reflejan en el filtro.

2022-02-11 15:27 UTC, Dara97 commented on src/components/formProducts/FormProducts.css
> +  outline: none;
Si, funciona para eliminar la sombra que se forma cuando se va a escribir en el input.

2022-02-11 17:17 UTC, elizabethriver commented on src/components/formProducts/FormProducts.css
> +  outline: none;
muy bueno!

2022-02-11 17:20 UTC, elizabethriver approved these changes
Buen trabajo chicas!

2022-02-16 14:24 UTC, merged